<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([['name' => "EL ENCANTO", 'department_id' => "1"],
            ['name' => "LA CHORRERA", 'department_id' => "1"],
            ['name' => "LA PEDRERA", 'department_id' => "1"],
            ['name' => "LA VICTORIA", 'department_id' => "1"],
            ['name' => "LETICIA", 'department_id' => "1"],
            ['name' => "MIRITI", 'department_id' => "1"],
            ['name' => "PUERTO ALEGRIA", 'department_id' => "1"],
            ['name' => "PUERTO ARICA", 'department_id' => "1"],
            ['name' => "PUERTO NARIÑO", 'department_id' => "1"],
            ['name' => "PUERTO SANTANDER", 'department_id' => "1"],
            ['name' => "TURAPACA", 'department_id' => "1"],
            ['name' => "ABEJORRAL", 'department_id' => "2"],
            ['name' => "ABRIAQUI", 'department_id' => "2"],
            ['name' => "ALEJANDRIA", 'department_id' => "2"],
            ['name' => "AMAGA", 'department_id' => "2"],
            ['name' => "AMALFI", 'department_id' => "2"],
            ['name' => "ANDES", 'department_id' => "2"],
            ['name' => "ANGELOPOLIS", 'department_id' => "2"],
            ['name' => "ANGOSTURA", 'department_id' => "2"],
            ['name' => "ANORI", 'department_id' => "2"],
            ['name' => "ANTIOQUIA", 'department_id' => "2"],
            ['name' => "ANZA", 'department_id' => "2"],
            ['name' => "APARTADO", 'department_id' => "2"],
            ['name' => "ARBOLETES", 'department_id' => "2"],
            ['name' => "ARGELIA", 'department_id' => "2"],
            ['name' => "ARMENIA", 'department_id' => "2"],
            ['name' => "BARBOSA", 'department_id' => "2"],
            ['name' => "BELLO", 'department_id' => "2"],
            ['name' => "BELMIRA", 'department_id' => "2"],
            ['name' => "BETANIA", 'department_id' => "2"],
            ['name' => "BETULIA", 'department_id' => "2"],
            ['name' => "BOLIVAR", 'department_id' => "2"],
            ['name' => "BRICEÑO", 'department_id' => "2"],
            ['name' => "BURITICA", 'department_id' => "2"],
            ['name' => "CACERES", 'department_id' => "2"],
            ['name' => "CAICEDO", 'department_id' => "2"],
            ['name' => "CALDAS", 'department_id' => "2"],
            ['name' => "CAMPAMENTO", 'department_id' => "2"],
            ['name' => "CANASGORDAS", 'department_id' => "2"],
            ['name' => "CARACOLI", 'department_id' => "2"],
            ['name' => "CARAMANTA", 'department_id' => "2"],
            ['name' => "CAREPA", 'department_id' => "2"],
            ['name' => "CARMEN DE VIBORAL", 'department_id' => "2"],
            ['name' => "CAROLINA DEL PRINCIPE", 'department_id' => "2"],
            ['name' => "CAUCASIA", 'department_id' => "2"],
            ['name' => "CHIGORODO", 'department_id' => "2"],
            ['name' => "CISNEROS", 'department_id' => "2"],
            ['name' => "COCORNA", 'department_id' => "2"],
            ['name' => "CONCEPCION", 'department_id' => "2"],
            ['name' => "CONCORDIA", 'department_id' => "2"],
            ['name' => "COPACABANA", 'department_id' => "2"],
            ['name' => "DABEIBA", 'department_id' => "2"],
            ['name' => "DONMATIAS", 'department_id' => "2"],
            ['name' => "EBEJICO", 'department_id' => "2"],
            ['name' => "EL BAGRE", 'department_id' => "2"],
            ['name' => "EL PENOL", 'department_id' => "2"],
            ['name' => "EL RETIRO", 'department_id' => "2"],
            ['name' => "ENTRERRIOS", 'department_id' => "2"],
            ['name' => "ENVIGADO", 'department_id' => "2"],
            ['name' => "FREDONIA", 'department_id' => "2"],
            ['name' => "FRONTINO", 'department_id' => "2"],
            ['name' => "GIRALDO", 'department_id' => "2"],
            ['name' => "GIRARDOTA", 'department_id' => "2"],
            ['name' => "GOMEZ PLATA", 'department_id' => "2"],
            ['name' => "GRANADA", 'department_id' => "2"],
            ['name' => "GUADALUPE", 'department_id' => "2"],
            ['name' => "GUARNE", 'department_id' => "2"],
            ['name' => "GUATAQUE", 'department_id' => "2"],
            ['name' => "HELICONIA", 'department_id' => "2"],
            ['name' => "HISPANIA", 'department_id' => "2"],
            ['name' => "ITAGUI", 'department_id' => "2"],
            ['name' => "ITUANGO", 'department_id' => "2"],
            ['name' => "JARDIN", 'department_id' => "2"],
            ['name' => "JERICO", 'department_id' => "2"],
            ['name' => "LA CEJA", 'department_id' => "2"],
            ['name' => "LA ESTRELLA", 'department_id' => "2"],
            ['name' => "LA PINTADA", 'department_id' => "2"],
            ['name' => "LA UNION", 'department_id' => "2"],
            ['name' => "LIBORINA", 'department_id' => "2"],
            ['name' => "MACEO", 'department_id' => "2"],
            ['name' => "MARINILLA", 'department_id' => "2"],
            ['name' => "MEDELLIN", 'department_id' => "2"],
            ['name' => "MONTEBELLO", 'department_id' => "2"],
            ['name' => "MURINDO", 'department_id' => "2"],
            ['name' => "MUTATA", 'department_id' => "2"],
            ['name' => "NARINO", 'department_id' => "2"],
            ['name' => "NECHI", 'department_id' => "2"],
            ['name' => "NECOCLI", 'department_id' => "2"],
            ['name' => "OLAYA", 'department_id' => "2"],
            ['name' => "PEQUE", 'department_id' => "2"],
            ['name' => "PUEBLORRICO", 'department_id' => "2"],
            ['name' => "PUERTO BERRIO", 'department_id' => "2"],
            ['name' => "PUERTO NARE", 'department_id' => "2"],
            ['name' => "PUERTO TRIUNFO", 'department_id' => "2"],
            ['name' => "REMEDIOS", 'department_id' => "2"],
            ['name' => "RIONEGRO", 'department_id' => "2"],
            ['name' => "SABANALARGA", 'department_id' => "2"],
            ['name' => "SABANETA", 'department_id' => "2"],
            ['name' => "SALGAR", 'department_id' => "2"],
            ['name' => "SAN ANDRES DE CUERQUIA", 'department_id' => "2"],
            ['name' => "SAN CARLOS", 'department_id' => "2"],
            ['name' => "SAN FRANCISCO", 'department_id' => "2"],
            ['name' => "SAN JERONIMO", 'department_id' => "2"],
            ['name' => "SAN JOSE DE LA MONTAÑA", 'department_id' => "2"],
            ['name' => "SAN JUAN DE URABA", 'department_id' => "2"],
            ['name' => "SAN LUIS", 'department_id' => "2"],
            ['name' => "SAN PEDRO DE LOS MILAGROS", 'department_id' => "2"],
            ['name' => "SAN PEDRO DE URABA", 'department_id' => "2"],
            ['name' => "SAN RAFAEL", 'department_id' => "2"],
            ['name' => "SAN ROQUE", 'department_id' => "2"],
            ['name' => "SAN VICENTE", 'department_id' => "2"],
            ['name' => "SANTA BARBARA", 'department_id' => "2"],
            ['name' => "SANTA ROSA DE OSOS", 'department_id' => "2"],
            ['name' => "SANTO DOMINGO", 'department_id' => "2"],
            ['name' => "SANTUARIO", 'department_id' => "2"],
            ['name' => "SEGOVIA", 'department_id' => "2"],
            ['name' => "SONSON", 'department_id' => "2"],
            ['name' => "SOPETRAN", 'department_id' => "2"],
            ['name' => "TAMESIS", 'department_id' => "2"],
            ['name' => "TARAZA", 'department_id' => "2"],
            ['name' => "TARSO", 'department_id' => "2"],
            ['name' => "TITIRIBI", 'department_id' => "2"],
            ['name' => "TOLEDO", 'department_id' => "2"],
            ['name' => "TURBO", 'department_id' => "2"],
            ['name' => "URAMITA", 'department_id' => "2"],
            ['name' => "URRAO", 'department_id' => "2"],
            ['name' => "VALDIVIA", 'department_id' => "2"],
            ['name' => "VALPARAISO", 'department_id' => "2"],
            ['name' => "VEGACHI", 'department_id' => "2"],
            ['name' => "VENECIA", 'department_id' => "2"],
            ['name' => "VIGIA DEL FUERTE", 'department_id' => "2"],
            ['name' => "YALI", 'department_id' => "2"],
            ['name' => "YARUMAL", 'department_id' => "2"],
            ['name' => "YOLOMBO", 'department_id' => "2"],
            ['name' => "YONDO", 'department_id' => "2"],
            ['name' => "ZARAGOZA", 'department_id' => "2"],


        ]);

        DB::table('cities')->insert([
            ['name' => "ARAUCA", 'department_id' => "3"],
            ['name' => "ARAUQUITA", 'department_id' => "3"],
            ['name' => "CRAVO NORTE", 'department_id' => "3"],
            ['name' => "FORTUL", 'department_id' => "3"],
            ['name' => "PUERTO RONDON", 'department_id' => "3"],
            ['name' => "SARAVENA", 'department_id' => "3"],
            ['name' => "TAME", 'department_id' => "3"],
            ['name' => "BARANOA", 'department_id' => "4"],
            ['name' => "BARRANQUILLA", 'department_id' => "4"],
            ['name' => "CAMPO DE LA CRUZ", 'department_id' => "4"],
            ['name' => "CANDELARIA", 'department_id' => "4"],
            ['name' => "GALAPA", 'department_id' => "4"],
            ['name' => "JUAN DE ACOSTA", 'department_id' => "4"],
            ['name' => "LURUACO", 'department_id' => "4"],
            ['name' => "MALAMBO", 'department_id' => "4"],
            ['name' => "MANATI", 'department_id' => "4"],
            ['name' => "PALMAR DE VARELA", 'department_id' => "4"],
            ['name' => "PIOJO", 'department_id' => "4"],
            ['name' => "POLO NUEVO", 'department_id' => "4"],
            ['name' => "PONEDERA", 'department_id' => "4"],
            ['name' => "PUERTO COLOMBIA", 'department_id' => "4"],
            ['name' => "REPELON", 'department_id' => "4"],
            ['name' => "SABANAGRANDE", 'department_id' => "4"],
            ['name' => "SABANALARGA", 'department_id' => "4"],
            ['name' => "SANTA LUCIA", 'department_id' => "4"],
            ['name' => "SANTO TOMAS", 'department_id' => "4"],
            ['name' => "SOLEDAD", 'department_id' => "4"],
            ['name' => "SUAN", 'department_id' => "4"],
            ['name' => "TUBARA", 'department_id' => "4"],
            ['name' => "USIACURI", 'department_id' => "4"],
            ['name' => "ACHI", 'department_id' => "5"],
            ['name' => "ALTOS DEL ROSARIO", 'department_id' => "5"],
            ['name' => "ARENAL", 'department_id' => "5"],
            ['name' => "ARJONA", 'department_id' => "5"],
            ['name' => "ARROYOHONDO", 'department_id' => "5"],
            ['name' => "BARRANCO DE LOBA", 'department_id' => "5"],
            ['name' => "BRAZUELO DE PAPAYAL", 'department_id' => "5"],
            ['name' => "CALAMAR", 'department_id' => "5"],
            ['name' => "CANTAGALLO", 'department_id' => "5"],
            ['name' => "CARTAGENA DE INDIAS", 'department_id' => "5"],
            ['name' => "CICUCO", 'department_id' => "5"],
            ['name' => "CLEMENCIA", 'department_id' => "5"],
            ['name' => "CORDOBA", 'department_id' => "5"],
            ['name' => "EL CARMEN DE BOLIVAR", 'department_id' => "5"],
            ['name' => "EL GUAMO", 'department_id' => "5"],
            ['name' => "EL PENION", 'department_id' => "5"],
            ['name' => "HATILLO DE LOBA", 'department_id' => "5"],
            ['name' => "MAGANGUE", 'department_id' => "5"],
            ['name' => "MAHATES", 'department_id' => "5"],
            ['name' => "MARGARITA", 'department_id' => "5"],
            ['name' => "MARIA LA BAJA", 'department_id' => "5"],
            ['name' => "MONTECRISTO", 'department_id' => "5"],
            ['name' => "MORALES", 'department_id' => "5"],
            ['name' => "MORALES", 'department_id' => "5"],
            ['name' => "NOROSI", 'department_id' => "5"],
            ['name' => "PINILLOS", 'department_id' => "5"],
            ['name' => "REGIDOR", 'department_id' => "5"],
            ['name' => "RIO VIEJO", 'department_id' => "5"],
            ['name' => "SAN CRISTOBAL", 'department_id' => "5"],
            ['name' => "SAN ESTANISLAO", 'department_id' => "5"],
            ['name' => "SAN FERNANDO", 'department_id' => "5"],
            ['name' => "SAN JACINTO", 'department_id' => "5"],
            ['name' => "SAN JACINTO DEL CAUCA", 'department_id' => "5"],
            ['name' => "SAN JUAN DE NEPOMUCENO", 'department_id' => "5"],
            ['name' => "SAN MARTIN DE LOBA", 'department_id' => "5"],
            ['name' => "SAN PABLO", 'department_id' => "5"],
            ['name' => "SAN PABLO NORTE", 'department_id' => "5"],
            ['name' => "SANTA CATALINA", 'department_id' => "5"],
            ['name' => "SANTA CRUZ DE MOMPOX", 'department_id' => "5"],
            ['name' => "SANTA ROSA", 'department_id' => "5"],
            ['name' => "SANTA ROSA DEL SUR", 'department_id' => "5"],
            ['name' => "SIMITI", 'department_id' => "5"],
            ['name' => "SOPLAVIENTO", 'department_id' => "5"],
            ['name' => "TALAIGUA NUEVO", 'department_id' => "5"],
            ['name' => "TUQUISIO", 'department_id' => "5"],
            ['name' => "TURBACO", 'department_id' => "5"],
            ['name' => "TURBANA", 'department_id' => "5"],
            ['name' => "VILLANUEVA", 'department_id' => "5"],
            ['name' => "ZAMBRANO", 'department_id' => "5"],
        ]);
        DB::table('cities')->insert([
            ['name' => "AQUITANIA", 'department_id' => "6"],
            ['name' => "ARCABUCO", 'department_id' => "6"],
            ['name' => "BELÉN", 'department_id' => "6"],
            ['name' => "BERBEO", 'department_id' => "6"],
            ['name' => "BETÉITIVA", 'department_id' => "6"],
            ['name' => "BOAVITA", 'department_id' => "6"],
            ['name' => "BOYACÁ", 'department_id' => "6"],
            ['name' => "BRICEÑO", 'department_id' => "6"],
            ['name' => "BUENAVISTA", 'department_id' => "6"],
            ['name' => "BUSBANZÁ", 'department_id' => "6"],
            ['name' => "CALDAS", 'department_id' => "6"],
            ['name' => "CAMPO HERMOSO", 'department_id' => "6"],
            ['name' => "CERINZA", 'department_id' => "6"],
            ['name' => "CHINAVITA", 'department_id' => "6"],
            ['name' => "CHIQUINQUIRÁ", 'department_id' => "6"],
            ['name' => "CHÍQUIZA", 'department_id' => "6"],
            ['name' => "CHISCAS", 'department_id' => "6"],
            ['name' => "CHITA", 'department_id' => "6"],
            ['name' => "CHITARAQUE", 'department_id' => "6"],
            ['name' => "CHIVATÁ", 'department_id' => "6"],
            ['name' => "CIÉNEGA", 'department_id' => "6"],
            ['name' => "CÓMBITA", 'department_id' => "6"],
            ['name' => "COPER", 'department_id' => "6"],
            ['name' => "CORRALES", 'department_id' => "6"],
            ['name' => "COVARACHÍA", 'department_id' => "6"],
            ['name' => "CUBARA", 'department_id' => "6"],
            ['name' => "CUCAITA", 'department_id' => "6"],
            ['name' => "CUITIVA", 'department_id' => "6"],
            ['name' => "DUITAMA", 'department_id' => "6"],
            ['name' => "EL COCUY", 'department_id' => "6"],
            ['name' => "EL ESPINO", 'department_id' => "6"],
            ['name' => "FIRAVITOBA", 'department_id' => "6"],
            ['name' => "FLORESTA", 'department_id' => "6"],
            ['name' => "GACHANTIVÁ", 'department_id' => "6"],
            ['name' => "GÁMEZA", 'department_id' => "6"],
            ['name' => "GARAGOA", 'department_id' => "6"],
            ['name' => "GUACAMAYAS", 'department_id' => "6"],
            ['name' => "GÜICÁN", 'department_id' => "6"],
            ['name' => "IZA", 'department_id' => "6"],
            ['name' => "JENESANO", 'department_id' => "6"],
            ['name' => "JERICÓ", 'department_id' => "6"],
            ['name' => "LA UVITA", 'department_id' => "6"],
            ['name' => "LA VICTORIA", 'department_id' => "6"],
            ['name' => "LABRANZA GRANDE", 'department_id' => "6"],
            ['name' => "MACANAL", 'department_id' => "6"],
            ['name' => "MARIPÍ", 'department_id' => "6"],
            ['name' => "MIRAFLORES", 'department_id' => "6"],
            ['name' => "MONGUA", 'department_id' => "6"],
            ['name' => "MONGUÍ", 'department_id' => "6"],
            ['name' => "MONIQUIRÁ", 'department_id' => "6"],
            ['name' => "MOTAVITA", 'department_id' => "6"],
            ['name' => "MUZO", 'department_id' => "6"],
            ['name' => "NOBSA", 'department_id' => "6"],
            ['name' => "NUEVO COLÓN", 'department_id' => "6"],
            ['name' => "OICATÁ", 'department_id' => "6"],
            ['name' => "OTANCHE", 'department_id' => "6"],
            ['name' => "PACHAVITA", 'department_id' => "6"],
            ['name' => "PÁEZ", 'department_id' => "6"],
            ['name' => "PAIPA", 'department_id' => "6"],
            ['name' => "PAJARITO", 'department_id' => "6"],
            ['name' => "PANQUEBA", 'department_id' => "6"],
            ['name' => "PAUNA", 'department_id' => "6"],
            ['name' => "PAYA", 'department_id' => "6"],
            ['name' => "PAZ DE RÍO", 'department_id' => "6"],
            ['name' => "PESCA", 'department_id' => "6"],
            ['name' => "PISBA", 'department_id' => "6"],
            ['name' => "PUERTO BOYACA", 'department_id' => "6"],
            ['name' => "QUÍPAMA", 'department_id' => "6"],
            ['name' => "RAMIRIQUÍ", 'department_id' => "6"],
            ['name' => "RÁQUIRA", 'department_id' => "6"],
            ['name' => "RONDÓN", 'department_id' => "6"],
            ['name' => "SABOYÁ", 'department_id' => "6"],
            ['name' => "SÁCHICA", 'department_id' => "6"],
            ['name' => "SAMACÁ", 'department_id' => "6"],
            ['name' => "SAN EDUARDO", 'department_id' => "6"],
            ['name' => "SAN JOSÉ DE PARE", 'department_id' => "6"],
            ['name' => "SAN LUÍS DE GACENO", 'department_id' => "6"],
            ['name' => "SAN MATEO", 'department_id' => "6"],
            ['name' => "SAN MIGUEL DE SEMA", 'department_id' => "6"],
            ['name' => "SAN PABLO DE BORBUR", 'department_id' => "6"],
            ['name' => "SANTA MARÍA", 'department_id' => "6"],
            ['name' => "SANTA ROSA DE VITERBO", 'department_id' => "6"],
            ['name' => "SANTA SOFÍA", 'department_id' => "6"],
            ['name' => "SANTANA", 'department_id' => "6"],
            ['name' => "SATIVANORTE", 'department_id' => "6"],
            ['name' => "SATIVASUR", 'department_id' => "6"],
            ['name' => "SIACHOQUE", 'department_id' => "6"],
            ['name' => "SOATÁ", 'department_id' => "6"],
            ['name' => "SOCHA", 'department_id' => "6"],
            ['name' => "SOCOTÁ", 'department_id' => "6"],
            ['name' => "SOGAMOSO", 'department_id' => "6"],
            ['name' => "SORA", 'department_id' => "6"],
            ['name' => "SORACÁ", 'department_id' => "6"],
            ['name' => "SOTAQUIRÁ", 'department_id' => "6"],
            ['name' => "SUSACÓN", 'department_id' => "6"],
            ['name' => "SUTARMACHÁN", 'department_id' => "6"],
            ['name' => "TASCO", 'department_id' => "6"],
            ['name' => "TIBANÁ", 'department_id' => "6"],
            ['name' => "TIBASOSA", 'department_id' => "6"],
            ['name' => "TINJACÁ", 'department_id' => "6"],
            ['name' => "TIPACOQUE", 'department_id' => "6"],
            ['name' => "TOCA", 'department_id' => "6"],
            ['name' => "TOGÜÍ", 'department_id' => "6"],
            ['name' => "TÓPAGA", 'department_id' => "6"],
            ['name' => "TOTA", 'department_id' => "6"],
            ['name' => "TUNJA", 'department_id' => "6"],
            ['name' => "TUNUNGUÁ", 'department_id' => "6"],
            ['name' => "TURMEQUÉ", 'department_id' => "6"],
            ['name' => "TUTA", 'department_id' => "6"],
            ['name' => "TUTAZÁ", 'department_id' => "6"],
            ['name' => "UMBITA", 'department_id' => "6"],
            ['name' => "VENTA QUEMADA", 'department_id' => "6"],
            ['name' => "VILLA DE LEYVA", 'department_id' => "6"],
            ['name' => "VIRACACHÁ", 'department_id' => "6"],
            ['name' => "ZETAQUIRA", 'department_id' => "6"],
            ['name' => "AGUADAS", 'department_id' => "7"],
            ['name' => "ANSERMA", 'department_id' => "7"],
            ['name' => "ARANZAZU", 'department_id' => "7"],
            ['name' => "BELALCAZAR", 'department_id' => "7"],
            ['name' => "CHINCHINÁ", 'department_id' => "7"],
            ['name' => "FILADELFIA", 'department_id' => "7"],
            ['name' => "LA DORADA", 'department_id' => "7"],
            ['name' => "LA MERCED", 'department_id' => "7"],
            ['name' => "MANIZALES", 'department_id' => "7"],
            ['name' => "MANZANARES", 'department_id' => "7"],
            ['name' => "MARMATO", 'department_id' => "7"],
            ['name' => "MARQUETALIA", 'department_id' => "7"],
            ['name' => "MARULANDA", 'department_id' => "7"],
            ['name' => "NEIRA", 'department_id' => "7"],
            ['name' => "NORCASIA", 'department_id' => "7"],
            ['name' => "PACORA", 'department_id' => "7"],
            ['name' => "PALESTINA", 'department_id' => "7"],
            ['name' => "PENSILVANIA", 'department_id' => "7"],
            ['name' => "RIOSUCIO", 'department_id' => "7"],
            ['name' => "RISARALDA", 'department_id' => "7"],
            ['name' => "SALAMINA", 'department_id' => "7"],
            ['name' => "SAMANA", 'department_id' => "7"],
            ['name' => "SAN JOSE", 'department_id' => "7"],
            ['name' => "SUPÍA", 'department_id' => "7"],
            ['name' => "VICTORIA", 'department_id' => "7"],
            ['name' => "VILLAMARÍA", 'department_id' => "7"],
            ['name' => "VITERBO", 'department_id' => "7"],
        ]);
        DB::table('cities')->insert([
            ['name' => "ALBANIA", 'department_id' => "8"],
            ['name' => "BELÉN ANDAQUIES", 'department_id' => "8"],
            ['name' => "CARTAGENA DEL CHAIRA", 'department_id' => "8"],
            ['name' => "CURILLO", 'department_id' => "8"],
            ['name' => "EL DONCELLO", 'department_id' => "8"],
            ['name' => "EL PAUJIL", 'department_id' => "8"],
            ['name' => "FLORENCIA", 'department_id' => "8"],
            ['name' => "LA MONTAÑITA", 'department_id' => "8"],
            ['name' => "MILÁN", 'department_id' => "8"],
            ['name' => "MORELIA", 'department_id' => "8"],
            ['name' => "PUERTO RICO", 'department_id' => "8"],
            ['name' => "SAN  VICENTE DEL CAGUAN", 'department_id' => "8"],
            ['name' => "SAN JOSÉ DE FRAGUA", 'department_id' => "8"],
            ['name' => "SOLANO", 'department_id' => "8"],
            ['name' => "SOLITA", 'department_id' => "8"],
            ['name' => "VALPARAÍSO", 'department_id' => "8"],
            ['name' => "AGUAZUL", 'department_id' => "9"],
            ['name' => "CHAMEZA", 'department_id' => "9"],
            ['name' => "HATO COROZAL", 'department_id' => "9"],
            ['name' => "LA SALINA", 'department_id' => "9"],
            ['name' => "MANÍ", 'department_id' => "9"],
            ['name' => "MONTERREY", 'department_id' => "9"],
            ['name' => "NUNCHIA", 'department_id' => "9"],
            ['name' => "OROCUE", 'department_id' => "9"],
            ['name' => "PAZ DE ARIPORO", 'department_id' => "9"],
            ['name' => "PORE", 'department_id' => "9"],
            ['name' => "RECETOR", 'department_id' => "9"],
            ['name' => "SABANA LARGA", 'department_id' => "9"],
            ['name' => "SACAMA", 'department_id' => "9"],
            ['name' => "SAN LUIS DE PALENQUE", 'department_id' => "9"],
            ['name' => "TAMARA", 'department_id' => "9"],
            ['name' => "TAURAMENA", 'department_id' => "9"],
            ['name' => "TRINIDAD", 'department_id' => "9"],
            ['name' => "VILLANUEVA", 'department_id' => "9"],
            ['name' => "YOPAL", 'department_id' => "9"],
            ['name' => "ALMAGUER", 'department_id' => "10"],
            ['name' => "ARGELIA", 'department_id' => "10"],
            ['name' => "BALBOA", 'department_id' => "10"],
            ['name' => "BOLÍVAR", 'department_id' => "10"],
            ['name' => "BUENOS AIRES", 'department_id' => "10"],
            ['name' => "CAJIBIO", 'department_id' => "10"],
            ['name' => "CALDONO", 'department_id' => "10"],
            ['name' => "CALOTO", 'department_id' => "10"],
            ['name' => "CORINTO", 'department_id' => "10"],
            ['name' => "EL TAMBO", 'department_id' => "10"],
            ['name' => "FLORENCIA", 'department_id' => "10"],
            ['name' => "GUAPI", 'department_id' => "10"],
            ['name' => "INZA", 'department_id' => "10"],
            ['name' => "JAMBALÓ", 'department_id' => "10"],
            ['name' => "LA SIERRA", 'department_id' => "10"],
            ['name' => "LA VEGA", 'department_id' => "10"],
            ['name' => "LÓPEZ", 'department_id' => "10"],
            ['name' => "MERCADERES", 'department_id' => "10"],
            ['name' => "MIRANDA", 'department_id' => "10"],
            ['name' => "MORALES", 'department_id' => "10"],
            ['name' => "PADILLA", 'department_id' => "10"],
            ['name' => "PÁEZ", 'department_id' => "10"],
            ['name' => "PATIA (EL BORDO)", 'department_id' => "10"],
            ['name' => "PIAMONTE", 'department_id' => "10"],
            ['name' => "PIENDAMO", 'department_id' => "10"],
            ['name' => "POPAYÁN", 'department_id' => "10"],
            ['name' => "PUERTO TEJADA", 'department_id' => "10"],
            ['name' => "PURACE", 'department_id' => "10"],
            ['name' => "ROSAS", 'department_id' => "10"],
            ['name' => "SAN SEBASTIÁN", 'department_id' => "10"],
            ['name' => "SANTA ROSA", 'department_id' => "10"],
            ['name' => "SANTANDER DE QUILICHAO", 'department_id' => "10"],
            ['name' => "SILVIA", 'department_id' => "10"],
            ['name' => "SOTARA", 'department_id' => "10"],
            ['name' => "SUÁREZ", 'department_id' => "10"],
            ['name' => "SUCRE", 'department_id' => "10"],
            ['name' => "TIMBÍO", 'department_id' => "10"],
            ['name' => "TIMBIQUÍ", 'department_id' => "10"],
            ['name' => "TORIBIO", 'department_id' => "10"],
            ['name' => "TOTORO", 'department_id' => "10"],
            ['name' => "VILLA RICA", 'department_id' => "10"],
        ]);
        DB::table('cities')->insert([
            ['name' => "AGUACHICA", 'department_id' => "11"],
            ['name' => "AGUSTÍN CODAZZI", 'department_id' => "11"],
            ['name' => "ASTREA", 'department_id' => "11"],
            ['name' => "BECERRIL", 'department_id' => "11"],
            ['name' => "BOSCONIA", 'department_id' => "11"],
            ['name' => "CHIMICHAGUA", 'department_id' => "11"],
            ['name' => "CHIRIGUANÁ", 'department_id' => "11"],
            ['name' => "CURUMANÍ", 'department_id' => "11"],
            ['name' => "EL COPEY", 'department_id' => "11"],
            ['name' => "EL PASO", 'department_id' => "11"],
            ['name' => "GAMARRA", 'department_id' => "11"],
            ['name' => "GONZÁLEZ", 'department_id' => "11"],
            ['name' => "LA GLORIA", 'department_id' => "11"],
            ['name' => "LA JAGUA IBIRICO", 'department_id' => "11"],
            ['name' => "MANAURE BALCÓN DEL CESAR", 'department_id' => "11"],
            ['name' => "PAILITAS", 'department_id' => "11"],
            ['name' => "PELAYA", 'department_id' => "11"],
            ['name' => "PUEBLO BELLO", 'department_id' => "11"],
            ['name' => "RÍO DE ORO", 'department_id' => "11"],
            ['name' => "ROBLES (LA PAZ)", 'department_id' => "11"],
            ['name' => "SAN ALBERTO", 'department_id' => "11"],
            ['name' => "SAN DIEGO", 'department_id' => "11"],
            ['name' => "SAN MARTÍN", 'department_id' => "11"],
            ['name' => "TAMALAMEQUE", 'department_id' => "11"],
            ['name' => "VALLEDUPAR", 'department_id' => "11"],
            ['name' => "ACANDI", 'department_id' => "12"],
            ['name' => "ALTO BAUDO (PIE DE PATO)", 'department_id' => "12"],
            ['name' => "ATRATO", 'department_id' => "12"],
            ['name' => "BAGADO", 'department_id' => "12"],
            ['name' => "BAHIA SOLANO (MUTIS)", 'department_id' => "12"],
            ['name' => "BAJO BAUDO (PIZARRO)", 'department_id' => "12"],
            ['name' => "BOJAYA (BELLAVISTA)", 'department_id' => "12"],
            ['name' => "CANTON DE SAN PABLO", 'department_id' => "12"],
            ['name' => "CARMEN DEL DARIEN", 'department_id' => "12"],
            ['name' => "CERTEGUI", 'department_id' => "12"],
            ['name' => "CONDOTO", 'department_id' => "12"],
            ['name' => "EL CARMEN", 'department_id' => "12"],
            ['name' => "ISTMINA", 'department_id' => "12"],
            ['name' => "JURADO", 'department_id' => "12"],
            ['name' => "LITORAL DEL SAN JUAN", 'department_id' => "12"],
            ['name' => "LLORO", 'department_id' => "12"],
            ['name' => "MEDIO ATRATO", 'department_id' => "12"],
            ['name' => "MEDIO BAUDO (BOCA DE PEPE)", 'department_id' => "12"],
            ['name' => "MEDIO SAN JUAN", 'department_id' => "12"],
            ['name' => "NOVITA", 'department_id' => "12"],
            ['name' => "NUQUI", 'department_id' => "12"],
            ['name' => "QUIBDO", 'department_id' => "12"],
            ['name' => "RIO IRO", 'department_id' => "12"],
            ['name' => "RIO QUITO", 'department_id' => "12"],
            ['name' => "RIOSUCIO", 'department_id' => "12"],
            ['name' => "SAN JOSE DEL PALMAR", 'department_id' => "12"],
            ['name' => "SIPI", 'department_id' => "12"],
            ['name' => "TADO", 'department_id' => "12"],
            ['name' => "UNGUIA", 'department_id' => "12"],
            ['name' => "UNIÓN PANAMERICANA", 'department_id' => "12"],
            ['name' => "AYAPEL", 'department_id' => "13"],
            ['name' => "BUENAVISTA", 'department_id' => "13"],
            ['name' => "CANALETE", 'department_id' => "13"],
            ['name' => "CERETÉ", 'department_id' => "13"],
            ['name' => "CHIMA", 'department_id' => "13"],
            ['name' => "CHINÚ", 'department_id' => "13"],
            ['name' => "CIENAGA DE ORO", 'department_id' => "13"],
            ['name' => "COTORRA", 'department_id' => "13"],
            ['name' => "LA APARTADA", 'department_id' => "13"],
            ['name' => "LORICA", 'department_id' => "13"],
            ['name' => "LOS CÓRDOBAS", 'department_id' => "13"],
            ['name' => "MOMIL", 'department_id' => "13"],
            ['name' => "MONTELÍBANO", 'department_id' => "13"],
            ['name' => "MONTERÍA", 'department_id' => "13"],
            ['name' => "MOÑITOS", 'department_id' => "13"],
            ['name' => "PLANETA RICA", 'department_id' => "13"],
            ['name' => "PUEBLO NUEVO", 'department_id' => "13"],
            ['name' => "PUERTO ESCONDIDO", 'department_id' => "13"],
            ['name' => "PUERTO LIBERTADOR", 'department_id' => "13"],
            ['name' => "PURÍSIMA", 'department_id' => "13"],
            ['name' => "SAHAGÚN", 'department_id' => "13"],
            ['name' => "SAN ANDRÉS SOTAVENTO", 'department_id' => "13"],
            ['name' => "SAN ANTERO", 'department_id' => "13"],
            ['name' => "SAN BERNARDO VIENTO", 'department_id' => "13"],
            ['name' => "SAN CARLOS", 'department_id' => "13"],
            ['name' => "SAN PELAYO", 'department_id' => "13"],
            ['name' => "TIERRALTA", 'department_id' => "13"],
            ['name' => "VALENCIA", 'department_id' => "13"],
        ]);
        DB::table('cities')->insert([
            ['name' => "AGUA DE DIOS", 'department_id' => "14"],
            ['name' => "ALBAN", 'department_id' => "14"],
            ['name' => "ANAPOIMA", 'department_id' => "14"],
            ['name' => "ANOLAIMA", 'department_id' => "14"],
            ['name' => "ARBELAEZ", 'department_id' => "14"],
            ['name' => "BELTRÁN", 'department_id' => "14"],
            ['name' => "BITUIMA", 'department_id' => "14"],
            ['name' => "BOGOTÁ DC", 'department_id' => "14"],
            ['name' => "BOJACÁ", 'department_id' => "14"],
            ['name' => "CABRERA", 'department_id' => "14"],
            ['name' => "CACHIPAY", 'department_id' => "14"],
            ['name' => "CAJICÁ", 'department_id' => "14"],
            ['name' => "CAPARRAPÍ", 'department_id' => "14"],
            ['name' => "CAQUEZA", 'department_id' => "14"],
            ['name' => "CARMEN DE CARUPA", 'department_id' => "14"],
            ['name' => "CHAGUANÍ", 'department_id' => "14"],
            ['name' => "CHIA", 'department_id' => "14"],
            ['name' => "CHIPAQUE", 'department_id' => "14"],
            ['name' => "CHOACHÍ", 'department_id' => "14"],
            ['name' => "CHOCONTÁ", 'department_id' => "14"],
            ['name' => "COGUA", 'department_id' => "14"],
            ['name' => "COTA", 'department_id' => "14"],
            ['name' => "CUCUNUBÁ", 'department_id' => "14"],
            ['name' => "EL COLEGIO", 'department_id' => "14"],
            ['name' => "EL PEÑÓN", 'department_id' => "14"],
            ['name' => "EL ROSAL1", 'department_id' => "14"],
            ['name' => "FACATATIVA", 'department_id' => "14"],
            ['name' => "FÓMEQUE", 'department_id' => "14"],
            ['name' => "FOSCA", 'department_id' => "14"],
            ['name' => "FUNZA", 'department_id' => "14"],
            ['name' => "FÚQUENE", 'department_id' => "14"],
            ['name' => "FUSAGASUGA", 'department_id' => "14"],
            ['name' => "GACHALÁ", 'department_id' => "14"],
            ['name' => "GACHANCIPÁ", 'department_id' => "14"],
            ['name' => "GACHETA", 'department_id' => "14"],
            ['name' => "GAMA", 'department_id' => "14"],
            ['name' => "GIRARDOT", 'department_id' => "14"],
            ['name' => "GRANADA2", 'department_id' => "14"],
            ['name' => "GUACHETÁ", 'department_id' => "14"],
            ['name' => "GUADUAS", 'department_id' => "14"],
            ['name' => "GUASCA", 'department_id' => "14"],
            ['name' => "GUATAQUÍ", 'department_id' => "14"],
            ['name' => "GUATAVITA", 'department_id' => "14"],
            ['name' => "GUAYABAL DE SIQUIMA", 'department_id' => "14"],
            ['name' => "GUAYABETAL", 'department_id' => "14"],
            ['name' => "GUTIÉRREZ", 'department_id' => "14"],
            ['name' => "JERUSALÉN", 'department_id' => "14"],
            ['name' => "JUNÍN", 'department_id' => "14"],
            ['name' => "LA CALERA", 'department_id' => "14"],
            ['name' => "LA MESA", 'department_id' => "14"],
            ['name' => "LA PALMA", 'department_id' => "14"],
            ['name' => "LA PEÑA", 'department_id' => "14"],
            ['name' => "LA VEGA", 'department_id' => "14"],
            ['name' => "LENGUAZAQUE", 'department_id' => "14"],
            ['name' => "MACHETÁ", 'department_id' => "14"],
            ['name' => "MADRID", 'department_id' => "14"],
            ['name' => "MANTA", 'department_id' => "14"],
            ['name' => "MEDINA", 'department_id' => "14"],
            ['name' => "MOSQUERA", 'department_id' => "14"],
            ['name' => "NARIÑO", 'department_id' => "14"],
            ['name' => "NEMOCÓN", 'department_id' => "14"],
            ['name' => "NILO", 'department_id' => "14"],
            ['name' => "NIMAIMA", 'department_id' => "14"],
            ['name' => "NOCAIMA", 'department_id' => "14"],
            ['name' => "OSPINA PÉREZ", 'department_id' => "14"],
            ['name' => "PACHO", 'department_id' => "14"],
            ['name' => "PAIME", 'department_id' => "14"],
            ['name' => "PANDI", 'department_id' => "14"],
            ['name' => "PARATEBUENO", 'department_id' => "14"],
            ['name' => "PASCA", 'department_id' => "14"],
            ['name' => "PUERTO SALGAR", 'department_id' => "14"],
            ['name' => "PULÍ", 'department_id' => "14"],
            ['name' => "QUEBRADANEGRA", 'department_id' => "14"],
            ['name' => "QUETAME", 'department_id' => "14"],
            ['name' => "QUIPILE", 'department_id' => "14"],
            ['name' => "RAFAEL REYES", 'department_id' => "14"],
            ['name' => "RICAURTE", 'department_id' => "14"],
            ['name' => "SAN  ANTONIO DEL  TEQUENDAMA", 'department_id' => "14"],
            ['name' => "SAN BERNARDO", 'department_id' => "14"],
            ['name' => "SAN CAYETANO", 'department_id' => "14"],
            ['name' => "SAN FRANCISCO", 'department_id' => "14"],
            ['name' => "SAN JUAN DE RIOSECO", 'department_id' => "14"],
            ['name' => "SASAIMA", 'department_id' => "14"],
            ['name' => "SESQUILÉ", 'department_id' => "14"],
            ['name' => "SIBATÉ", 'department_id' => "14"],
            ['name' => "SILVANIA", 'department_id' => "14"],
            ['name' => "SIMIJACA", 'department_id' => "14"],
            ['name' => "SOACHA", 'department_id' => "14"],
            ['name' => "SOPO", 'department_id' => "14"],
            ['name' => "SUBACHOQUE", 'department_id' => "14"],
            ['name' => "SUESCA", 'department_id' => "14"],
            ['name' => "SUPATÁ", 'department_id' => "14"],
            ['name' => "SUSA", 'department_id' => "14"],
            ['name' => "SUTATAUSA", 'department_id' => "14"],
            ['name' => "TABIO", 'department_id' => "14"],
            ['name' => "TAUSA", 'department_id' => "14"],
            ['name' => "TENA", 'department_id' => "14"],
            ['name' => "TENJO", 'department_id' => "14"],
            ['name' => "TIBACUY", 'department_id' => "14"],
            ['name' => "TIBIRITA", 'department_id' => "14"],
            ['name' => "TOCAIMA", 'department_id' => "14"],
            ['name' => "TOCANCIPÁ", 'department_id' => "14"],
            ['name' => "TOPAIPÍ", 'department_id' => "14"],
            ['name' => "UBALÁ", 'department_id' => "14"],
            ['name' => "UBAQUE", 'department_id' => "14"],
            ['name' => "UBATÉ", 'department_id' => "14"],
            ['name' => "UNE", 'department_id' => "14"],
            ['name' => "UTICA", 'department_id' => "14"],
            ['name' => "VERGARA", 'department_id' => "14"],
            ['name' => "VIANI", 'department_id' => "14"],
            ['name' => "VILLA GOMEZ", 'department_id' => "14"],
            ['name' => "VILLA PINZÓN", 'department_id' => "14"],
            ['name' => "VILLETA", 'department_id' => "14"],
            ['name' => "VIOTA", 'department_id' => "14"],
            ['name' => "YACOPÍ", 'department_id' => "14"],
            ['name' => "ZIPACÓN", 'department_id' => "14"],
            ['name' => "ZIPAQUIRÁ", 'department_id' => "14"],
            ['name' => "BARRANCO MINAS", 'department_id' => "15"],
            ['name' => "CACAHUAL", 'department_id' => "15"],
            ['name' => "INÍRIDA", 'department_id' => "15"],
            ['name' => "LA GUADALUPE", 'department_id' => "15"],
            ['name' => "MAPIRIPANA", 'department_id' => "15"],
            ['name' => "MORICHAL", 'department_id' => "15"],
            ['name' => "PANA PANA", 'department_id' => "15"],
            ['name' => "PUERTO COLOMBIA", 'department_id' => "15"],
            ['name' => "SAN FELIPE", 'department_id' => "15"],
        ]);
        DB::table('cities')->insert([
            ['name' => "CALAMAR", 'department_id' => "16"],
            ['name' => "EL RETORNO", 'department_id' => "16"],
            ['name' => "MIRAFLOREZ", 'department_id' => "16"],
            ['name' => "SAN JOSÉ DEL GUAVIARE", 'department_id' => "16"],
            ['name' => "ACEVEDO", 'department_id' => "17"],
            ['name' => "AGRADO", 'department_id' => "17"],
            ['name' => "AIPE", 'department_id' => "17"],
            ['name' => "ALGECIRAS", 'department_id' => "17"],
            ['name' => "ALTAMIRA", 'department_id' => "17"],
            ['name' => "BARAYA", 'department_id' => "17"],
            ['name' => "CAMPO ALEGRE", 'department_id' => "17"],
            ['name' => "COLOMBIA", 'department_id' => "17"],
            ['name' => "ELIAS", 'department_id' => "17"],
            ['name' => "GARZÓN", 'department_id' => "17"],
            ['name' => "GIGANTE", 'department_id' => "17"],
            ['name' => "GUADALUPE", 'department_id' => "17"],
            ['name' => "HOBO", 'department_id' => "17"],
            ['name' => "IQUIRA", 'department_id' => "17"],
            ['name' => "ISNOS", 'department_id' => "17"],
            ['name' => "LA ARGENTINA", 'department_id' => "17"],
            ['name' => "LA PLATA", 'department_id' => "17"],
            ['name' => "NATAGA", 'department_id' => "17"],
            ['name' => "NEIVA", 'department_id' => "17"],
            ['name' => "OPORAPA", 'department_id' => "17"],
            ['name' => "PAICOL", 'department_id' => "17"],
            ['name' => "PALERMO", 'department_id' => "17"],
            ['name' => "PALESTINA", 'department_id' => "17"],
            ['name' => "PITAL", 'department_id' => "17"],
            ['name' => "PITALITO", 'department_id' => "17"],
            ['name' => "RIVERA", 'department_id' => "17"],
            ['name' => "SALADO BLANCO", 'department_id' => "17"],
            ['name' => "SAN AGUSTÍN", 'department_id' => "17"],
            ['name' => "SANTA MARIA", 'department_id' => "17"],
            ['name' => "SUAZA", 'department_id' => "17"],
            ['name' => "TARQUI", 'department_id' => "17"],
            ['name' => "TELLO", 'department_id' => "17"],
            ['name' => "TERUEL", 'department_id' => "17"],
            ['name' => "TESALIA", 'department_id' => "17"],
            ['name' => "TIMANA", 'department_id' => "17"],
            ['name' => "VILLAVIEJA", 'department_id' => "17"],
            ['name' => "YAGUARA", 'department_id' => "17"],
            ['name' => "ALBANIA", 'department_id' => "18"],
            ['name' => "BARRANCAS", 'department_id' => "18"],
            ['name' => "DIBULLA", 'department_id' => "18"],
            ['name' => "DISTRACCIÓN", 'department_id' => "18"],
            ['name' => "EL MOLINO", 'department_id' => "18"],
            ['name' => "FONSECA", 'department_id' => "18"],
            ['name' => "HATO NUEVO", 'department_id' => "18"],
            ['name' => "LA JAGUA DEL PILAR", 'department_id' => "18"],
            ['name' => "MAICAO", 'department_id' => "18"],
            ['name' => "MANAURE", 'department_id' => "18"],
            ['name' => "RIOHACHA", 'department_id' => "18"],
            ['name' => "SAN JUAN DEL CESAR", 'department_id' => "18"],
            ['name' => "URIBIA", 'department_id' => "18"],
            ['name' => "URUMITA", 'department_id' => "18"],
            ['name' => "VILLANUEVA", 'department_id' => "18"],
        ]);
        DB::table('cities')->insert([
            ['name' => "ALGARROBO", 'department_id' => "19"],
            ['name' => "ARACATACA", 'department_id' => "19"],
            ['name' => "ARIGUANI", 'department_id' => "19"],
            ['name' => "CERRO SAN ANTONIO", 'department_id' => "19"],
            ['name' => "CHIVOLO", 'department_id' => "19"],
            ['name' => "CIENAGA", 'department_id' => "19"],
            ['name' => "CONCORDIA", 'department_id' => "19"],
            ['name' => "EL BANCO", 'department_id' => "19"],
            ['name' => "EL PIÑON", 'department_id' => "19"],
            ['name' => "EL RETEN", 'department_id' => "19"],
            ['name' => "FUNDACION", 'department_id' => "19"],
            ['name' => "GUAMAL", 'department_id' => "19"],
            ['name' => "NUEVA GRANADA", 'department_id' => "19"],
            ['name' => "PEDRAZA", 'department_id' => "19"],
            ['name' => "PIJIÑO DEL CARMEN", 'department_id' => "19"],
            ['name' => "PIVIJAY", 'department_id' => "19"],
            ['name' => "PLATO", 'department_id' => "19"],
            ['name' => "PUEBLO VIEJO", 'department_id' => "19"],
            ['name' => "REMOLINO", 'department_id' => "19"],
            ['name' => "SABANAS DE SAN ANGEL", 'department_id' => "19"],
            ['name' => "SALAMINA", 'department_id' => "19"],
            ['name' => "SAN SEBASTIAN DE BUENAVISTA", 'department_id' => "19"],
            ['name' => "SAN ZENON", 'department_id' => "19"],
            ['name' => "SANTA ANA", 'department_id' => "19"],
            ['name' => "SANTA BARBARA DE PINTO", 'department_id' => "19"],
            ['name' => "SANTA MARTA", 'department_id' => "19"],
            ['name' => "SITIONUEVO", 'department_id' => "19"],
            ['name' => "TENERIFE", 'department_id' => "19"],
            ['name' => "ZAPAYAN", 'department_id' => "19"],
            ['name' => "ZONA BANANERA", 'department_id' => "19"],
            ['name' => "ACACIAS", 'department_id' => "20"],
            ['name' => "BARRANCA DE UPIA", 'department_id' => "20"],
            ['name' => "CABUYARO", 'department_id' => "20"],
            ['name' => "CASTILLA LA NUEVA", 'department_id' => "20"],
            ['name' => "CUBARRAL", 'department_id' => "20"],
            ['name' => "CUMARAL", 'department_id' => "20"],
            ['name' => "EL CALVARIO", 'department_id' => "20"],
            ['name' => "EL CASTILLO", 'department_id' => "20"],
            ['name' => "EL DORADO", 'department_id' => "20"],
            ['name' => "FUENTE DE ORO", 'department_id' => "20"],
            ['name' => "GRANADA", 'department_id' => "20"],
            ['name' => "GUAMAL", 'department_id' => "20"],
            ['name' => "LA MACARENA", 'department_id' => "20"],
            ['name' => "LA URIBE", 'department_id' => "20"],
            ['name' => "LEJANÍAS", 'department_id' => "20"],
            ['name' => "MAPIRIPÁN", 'department_id' => "20"],
            ['name' => "MESETAS", 'department_id' => "20"],
            ['name' => "PUERTO CONCORDIA", 'department_id' => "20"],
            ['name' => "PUERTO GAITÁN", 'department_id' => "20"],
            ['name' => "PUERTO LLERAS", 'department_id' => "20"],
            ['name' => "PUERTO LÓPEZ", 'department_id' => "20"],
            ['name' => "PUERTO RICO", 'department_id' => "20"],
            ['name' => "RESTREPO", 'department_id' => "20"],
            ['name' => "SAN  JUAN DE ARAMA", 'department_id' => "20"],
            ['name' => "SAN CARLOS GUAROA", 'department_id' => "20"],
            ['name' => "SAN JUANITO", 'department_id' => "20"],
            ['name' => "SAN MARTÍN", 'department_id' => "20"],
            ['name' => "VILLAVICENCIO", 'department_id' => "20"],
            ['name' => "VISTA HERMOSA", 'department_id' => "20"],
            ['name' => "ALBAN", 'department_id' => "21"],
            ['name' => "ALDAÑA", 'department_id' => "21"],
            ['name' => "ANCUYA", 'department_id' => "21"],
            ['name' => "ARBOLEDA", 'department_id' => "21"],
            ['name' => "BARBACOAS", 'department_id' => "21"],
            ['name' => "BELEN", 'department_id' => "21"],
            ['name' => "BUESACO", 'department_id' => "21"],
            ['name' => "CHACHAGUI", 'department_id' => "21"],
            ['name' => "COLON (GENOVA)", 'department_id' => "21"],
            ['name' => "CONSACA", 'department_id' => "21"],
            ['name' => "CONTADERO", 'department_id' => "21"],
            ['name' => "CORDOBA", 'department_id' => "21"],
            ['name' => "CUASPUD", 'department_id' => "21"],
            ['name' => "CUMBAL", 'department_id' => "21"],
            ['name' => "CUMBITARA", 'department_id' => "21"],
            ['name' => "EL CHARCO", 'department_id' => "21"],
            ['name' => "EL PEÑOL", 'department_id' => "21"],
            ['name' => "EL ROSARIO", 'department_id' => "21"],
            ['name' => "EL TABLÓN", 'department_id' => "21"],
            ['name' => "EL TAMBO", 'department_id' => "21"],
            ['name' => "FUNES", 'department_id' => "21"],
            ['name' => "GUACHUCAL", 'department_id' => "21"],
            ['name' => "GUAITARILLA", 'department_id' => "21"],
            ['name' => "GUALMATAN", 'department_id' => "21"],
            ['name' => "ILES", 'department_id' => "21"],
            ['name' => "IMUES", 'department_id' => "21"],
            ['name' => "IPIALES", 'department_id' => "21"],
            ['name' => "LA CRUZ", 'department_id' => "21"],
            ['name' => "LA FLORIDA", 'department_id' => "21"],
            ['name' => "LA LLANADA", 'department_id' => "21"],
            ['name' => "LA TOLA", 'department_id' => "21"],
            ['name' => "LA UNION", 'department_id' => "21"],
            ['name' => "LEIVA", 'department_id' => "21"],
            ['name' => "LINARES", 'department_id' => "21"],
            ['name' => "LOS ANDES", 'department_id' => "21"],
            ['name' => "MAGUI", 'department_id' => "21"],
            ['name' => "MALLAMA", 'department_id' => "21"],
            ['name' => "MOSQUEZA", 'department_id' => "21"],
            ['name' => "NARIÑO", 'department_id' => "21"],
            ['name' => "OLAYA HERRERA", 'department_id' => "21"],
            ['name' => "OSPINA", 'department_id' => "21"],
            ['name' => "PASTO", 'department_id' => "21"],
            ['name' => "PIZARRO", 'department_id' => "21"],
            ['name' => "POLICARPA", 'department_id' => "21"],
            ['name' => "POTOSI", 'department_id' => "21"],
            ['name' => "PROVIDENCIA", 'department_id' => "21"],
            ['name' => "PUERRES", 'department_id' => "21"],
            ['name' => "PUPIALES", 'department_id' => "21"],
            ['name' => "RICAURTE", 'department_id' => "21"],
            ['name' => "ROBERTO PAYAN", 'department_id' => "21"],
            ['name' => "SAMANIEGO", 'department_id' => "21"],
            ['name' => "SAN BERNARDO", 'department_id' => "21"],
            ['name' => "SAN LORENZO", 'department_id' => "21"],
            ['name' => "SAN PABLO", 'department_id' => "21"],
            ['name' => "SAN PEDRO DE CARTAGO", 'department_id' => "21"],
            ['name' => "SANDONA", 'department_id' => "21"],
            ['name' => "SANTA BARBARA", 'department_id' => "21"],
            ['name' => "SANTACRUZ", 'department_id' => "21"],
            ['name' => "SAPUYES", 'department_id' => "21"],
            ['name' => "TAMINANGO", 'department_id' => "21"],
            ['name' => "TANGUA", 'department_id' => "21"],
            ['name' => "TUMACO", 'department_id' => "21"],
            ['name' => "TUQUERRES", 'department_id' => "21"],
            ['name' => "YACUANQUER", 'department_id' => "21"],
        ]);
        DB::table('cities')->insert([
            ['name' => "ABREGO", 'department_id' => "22"],
            ['name' => "ARBOLEDAS", 'department_id' => "22"],
            ['name' => "BOCHALEMA", 'department_id' => "22"],
            ['name' => "BUCARASICA", 'department_id' => "22"],
            ['name' => "CÁCHIRA", 'department_id' => "22"],
            ['name' => "CÁCOTA", 'department_id' => "22"],
            ['name' => "CHINÁCOTA", 'department_id' => "22"],
            ['name' => "CHITAGÁ", 'department_id' => "22"],
            ['name' => "CONVENCIÓN", 'department_id' => "22"],
            ['name' => "CÚCUTA", 'department_id' => "22"],
            ['name' => "CUCUTILLA", 'department_id' => "22"],
            ['name' => "DURANIA", 'department_id' => "22"],
            ['name' => "EL CARMEN", 'department_id' => "22"],
            ['name' => "EL TARRA", 'department_id' => "22"],
            ['name' => "EL ZULIA", 'department_id' => "22"],
            ['name' => "GRAMALOTE", 'department_id' => "22"],
            ['name' => "HACARI", 'department_id' => "22"],
            ['name' => "HERRÁN", 'department_id' => "22"],
            ['name' => "LA ESPERANZA", 'department_id' => "22"],
            ['name' => "LA PLAYA", 'department_id' => "22"],
            ['name' => "LABATECA", 'department_id' => "22"],
            ['name' => "LOS PATIOS", 'department_id' => "22"],
            ['name' => "LOURDES", 'department_id' => "22"],
            ['name' => "MUTISCUA", 'department_id' => "22"],
            ['name' => "OCAÑA", 'department_id' => "22"],
            ['name' => "PAMPLONA", 'department_id' => "22"],
            ['name' => "PAMPLONITA", 'department_id' => "22"],
            ['name' => "PUERTO SANTANDER", 'department_id' => "22"],
            ['name' => "RAGONVALIA", 'department_id' => "22"],
            ['name' => "SALAZAR", 'department_id' => "22"],
            ['name' => "SAN CALIXTO", 'department_id' => "22"],
            ['name' => "SAN CAYETANO", 'department_id' => "22"],
            ['name' => "SANTIAGO", 'department_id' => "22"],
            ['name' => "SARDINATA", 'department_id' => "22"],
            ['name' => "SILOS", 'department_id' => "22"],
            ['name' => "TEORAMA", 'department_id' => "22"],
            ['name' => "TIBÚ", 'department_id' => "22"],
            ['name' => "TOLEDO", 'department_id' => "22"],
            ['name' => "VILLA CARO", 'department_id' => "22"],
            ['name' => "VILLA DEL ROSARIO", 'department_id' => "22"],
            ['name' => "COLÓN", 'department_id' => "23"],
            ['name' => "MOCOA", 'department_id' => "23"],
            ['name' => "ORITO", 'department_id' => "23"],
            ['name' => "PUERTO ASÍS", 'department_id' => "23"],
            ['name' => "PUERTO CAYCEDO", 'department_id' => "23"],
            ['name' => "PUERTO GUZMÁN", 'department_id' => "23"],
            ['name' => "PUERTO LEGUÍZAMO", 'department_id' => "23"],
            ['name' => "SAN FRANCISCO", 'department_id' => "23"],
            ['name' => "SAN MIGUEL", 'department_id' => "23"],
            ['name' => "SANTIAGO", 'department_id' => "23"],
            ['name' => "SIBUNDOY", 'department_id' => "23"],
            ['name' => "VALLE DEL GUAMUEZ", 'department_id' => "23"],
            ['name' => "VILLAGARZÓN", 'department_id' => "23"],
            ['name' => "ARMENIA", 'department_id' => "24"],
            ['name' => "BUENAVISTA", 'department_id' => "24"],
            ['name' => "CALARCÁ", 'department_id' => "24"],
            ['name' => "CIRCASIA", 'department_id' => "24"],
            ['name' => "CÓRDOBA", 'department_id' => "24"],
            ['name' => "FILANDIA", 'department_id' => "24"],
            ['name' => "GÉNOVA", 'department_id' => "24"],
            ['name' => "LA TEBAIDA", 'department_id' => "24"],
            ['name' => "MONTENEGRO", 'department_id' => "24"],
            ['name' => "PIJAO", 'department_id' => "24"],
            ['name' => "QUIMBAYA", 'department_id' => "24"],
            ['name' => "SALENTO", 'department_id' => "24"],
            ['name' => "APIA", 'department_id' => "25"],
            ['name' => "BALBOA", 'department_id' => "25"],
            ['name' => "BELÉN DE UMBRÍA", 'department_id' => "25"],
            ['name' => "DOS QUEBRADAS", 'department_id' => "25"],
            ['name' => "GUATICA", 'department_id' => "25"],
            ['name' => "LA CELIA", 'department_id' => "25"],
            ['name' => "LA VIRGINIA", 'department_id' => "25"],
            ['name' => "MARSELLA", 'department_id' => "25"],
            ['name' => "MISTRATO", 'department_id' => "25"],
            ['name' => "PEREIRA", 'department_id' => "25"],
            ['name' => "PUEBLO RICO", 'department_id' => "25"],
            ['name' => "QUINCHÍA", 'department_id' => "25"],
            ['name' => "SANTA ROSA DE CABAL", 'department_id' => "25"],
            ['name' => "SANTUARIO", 'department_id' => "25"],
            ['name' => "PROVIDENCIA", 'department_id' => "26"],
            ['name' => "SAN ANDRES", 'department_id' => "26"],
            ['name' => "SANTA CATALINA", 'department_id' => "26"],
        ]);
        DB::table('cities')->insert([
            ['name' => "AGUADA", 'department_id' => "27"],
            ['name' => "ALBANIA", 'department_id' => "27"],
            ['name' => "ARATOCA", 'department_id' => "27"],
            ['name' => "BARBOSA", 'department_id' => "27"],
            ['name' => "BARICHARA", 'department_id' => "27"],
            ['name' => "BARRANCABERMEJA", 'department_id' => "27"],
            ['name' => "BETULIA", 'department_id' => "27"],
            ['name' => "BOLÍVAR", 'department_id' => "27"],
            ['name' => "BUCARAMANGA", 'department_id' => "27"],
            ['name' => "CABRERA", 'department_id' => "27"],
            ['name' => "CALIFORNIA", 'department_id' => "27"],
            ['name' => "CAPITANEJO", 'department_id' => "27"],
            ['name' => "CARCASI", 'department_id' => "27"],
            ['name' => "CEPITA", 'department_id' => "27"],
            ['name' => "CERRITO", 'department_id' => "27"],
            ['name' => "CHARALÁ", 'department_id' => "27"],
            ['name' => "CHARTA", 'department_id' => "27"],
            ['name' => "CHIMA", 'department_id' => "27"],
            ['name' => "CHIPATÁ", 'department_id' => "27"],
            ['name' => "CIMITARRA", 'department_id' => "27"],
            ['name' => "CONCEPCIÓN", 'department_id' => "27"],
            ['name' => "CONFINES", 'department_id' => "27"],
            ['name' => "CONTRATACIÓN", 'department_id' => "27"],
            ['name' => "COROMORO", 'department_id' => "27"],
            ['name' => "CURITÍ", 'department_id' => "27"],
            ['name' => "EL CARMEN", 'department_id' => "27"],
            ['name' => "EL GUACAMAYO", 'department_id' => "27"],
            ['name' => "EL PEÑÓN", 'department_id' => "27"],
            ['name' => "EL PLAYÓN", 'department_id' => "27"],
            ['name' => "ENCINO", 'department_id' => "27"],
            ['name' => "ENCISO", 'department_id' => "27"],
            ['name' => "FLORIÁN", 'department_id' => "27"],
            ['name' => "FLORIDABLANCA", 'department_id' => "27"],
            ['name' => "GALÁN", 'department_id' => "27"],
            ['name' => "GAMBITA", 'department_id' => "27"],
            ['name' => "GIRÓN", 'department_id' => "27"],
            ['name' => "GUACA", 'department_id' => "27"],
            ['name' => "GUADALUPE", 'department_id' => "27"],
            ['name' => "GUAPOTA", 'department_id' => "27"],
            ['name' => "GUAVATÁ", 'department_id' => "27"],
            ['name' => "GUEPSA", 'department_id' => "27"],
            ['name' => "HATO", 'department_id' => "27"],
            ['name' => "JESÚS MARIA", 'department_id' => "27"],
            ['name' => "JORDÁN", 'department_id' => "27"],
            ['name' => "LA BELLEZA", 'department_id' => "27"],
            ['name' => "LA PAZ", 'department_id' => "27"],
            ['name' => "LANDAZURI", 'department_id' => "27"],
            ['name' => "LEBRIJA", 'department_id' => "27"],
            ['name' => "LOS SANTOS", 'department_id' => "27"],
            ['name' => "MACARAVITA", 'department_id' => "27"],
            ['name' => "MÁLAGA", 'department_id' => "27"],
            ['name' => "MATANZA", 'department_id' => "27"],
            ['name' => "MOGOTES", 'department_id' => "27"],
            ['name' => "MOLAGAVITA", 'department_id' => "27"],
            ['name' => "OCAMONTE", 'department_id' => "27"],
            ['name' => "OIBA", 'department_id' => "27"],
            ['name' => "ONZAGA", 'department_id' => "27"],
            ['name' => "PALMAR", 'department_id' => "27"],
            ['name' => "PALMAS DEL SOCORRO", 'department_id' => "27"],
            ['name' => "PÁRAMO", 'department_id' => "27"],
            ['name' => "PIEDECUESTA", 'department_id' => "27"],
            ['name' => "PINCHOTE", 'department_id' => "27"],
            ['name' => "PUENTE NACIONAL", 'department_id' => "27"],
            ['name' => "PUERTO PARRA", 'department_id' => "27"],
            ['name' => "PUERTO WILCHES", 'department_id' => "27"],
            ['name' => "RIONEGRO", 'department_id' => "27"],
            ['name' => "SABANA DE TORRES", 'department_id' => "27"],
            ['name' => "SAN ANDRÉS", 'department_id' => "27"],
            ['name' => "SAN BENITO", 'department_id' => "27"],
            ['name' => "SAN GIL", 'department_id' => "27"],
            ['name' => "SAN JOAQUÍN", 'department_id' => "27"],
            ['name' => "SAN JOSÉ DE MIRANDA", 'department_id' => "27"],
            ['name' => "SAN MIGUEL", 'department_id' => "27"],
            ['name' => "SAN VICENTE DE CHUCURÍ", 'department_id' => "27"],
            ['name' => "SANTA BÁRBARA", 'department_id' => "27"],
            ['name' => "SANTA HELENA", 'department_id' => "27"],
            ['name' => "SIMACOTA", 'department_id' => "27"],
            ['name' => "SOCORRO", 'department_id' => "27"],
            ['name' => "SUAITA", 'department_id' => "27"],
            ['name' => "SUCRE", 'department_id' => "27"],
            ['name' => "SURATA", 'department_id' => "27"],
            ['name' => "TONA", 'department_id' => "27"],
            ['name' => "VALLE SAN JOSÉ", 'department_id' => "27"],
            ['name' => "VÉLEZ", 'department_id' => "27"],
            ['name' => "VETAS", 'department_id' => "27"],
            ['name' => "VILLANUEVA", 'department_id' => "27"],
            ['name' => "ZAPATOCA", 'department_id' => "27"],
            ['name' => "BUENAVISTA", 'department_id' => "28"],
            ['name' => "CAIMITO", 'department_id' => "28"],
            ['name' => "CHALÁN", 'department_id' => "28"],
            ['name' => "COLOSO", 'department_id' => "28"],
            ['name' => "COROZAL", 'department_id' => "28"],
            ['name' => "EL ROBLE", 'department_id' => "28"],
            ['name' => "GALERAS", 'department_id' => "28"],
            ['name' => "GUARANDA", 'department_id' => "28"],
            ['name' => "LA UNIÓN", 'department_id' => "28"],
            ['name' => "LOS PALMITOS", 'department_id' => "28"],
            ['name' => "MAJAGUAL", 'department_id' => "28"],
            ['name' => "MORROA", 'department_id' => "28"],
            ['name' => "OVEJAS", 'department_id' => "28"],
            ['name' => "PALMITO", 'department_id' => "28"],
            ['name' => "SAMPUES", 'department_id' => "28"],
            ['name' => "SAN BENITO ABAD", 'department_id' => "28"],
            ['name' => "SAN JUAN DE BETULIA", 'department_id' => "28"],
            ['name' => "SAN MARCOS", 'department_id' => "28"],
            ['name' => "SAN ONOFRE", 'department_id' => "28"],
            ['name' => "SAN PEDRO", 'department_id' => "28"],
            ['name' => "SINCÉ", 'department_id' => "28"],
            ['name' => "SINCELEJO", 'department_id' => "28"],
            ['name' => "SUCRE", 'department_id' => "28"],
            ['name' => "TOLÚ", 'department_id' => "28"],
            ['name' => "TOLUVIEJO", 'department_id' => "28"],
            ['name' => "ALPUJARRA", 'department_id' => "29"],
            ['name' => "ALVARADO", 'department_id' => "29"],
            ['name' => "AMBALEMA", 'department_id' => "29"],
            ['name' => "ANZOATEGUI", 'department_id' => "29"],
            ['name' => "ARMERO (GUAYABAL)", 'department_id' => "29"],
            ['name' => "ATACO", 'department_id' => "29"],
            ['name' => "CAJAMARCA", 'department_id' => "29"],
            ['name' => "CARMEN DE APICALÁ", 'department_id' => "29"],
            ['name' => "CASABIANCA", 'department_id' => "29"],
            ['name' => "CHAPARRAL", 'department_id' => "29"],
            ['name' => "COELLO", 'department_id' => "29"],
            ['name' => "COYAIMA", 'department_id' => "29"],
            ['name' => "CUNDAY", 'department_id' => "29"],
            ['name' => "DOLORES", 'department_id' => "29"],
            ['name' => "ESPINAL", 'department_id' => "29"],
            ['name' => "FALÁN", 'department_id' => "29"],
            ['name' => "FLANDES", 'department_id' => "29"],
            ['name' => "FRESNO", 'department_id' => "29"],
            ['name' => "GUAMO", 'department_id' => "29"],
            ['name' => "HERVEO", 'department_id' => "29"],
            ['name' => "HONDA", 'department_id' => "29"],
            ['name' => "IBAGUÉ", 'department_id' => "29"],
            ['name' => "ICONONZO", 'department_id' => "29"],
            ['name' => "LÉRIDA", 'department_id' => "29"],
            ['name' => "LÍBANO", 'department_id' => "29"],
            ['name' => "MARIQUITA", 'department_id' => "29"],
            ['name' => "MELGAR", 'department_id' => "29"],
            ['name' => "MURILLO", 'department_id' => "29"],
            ['name' => "NATAGAIMA", 'department_id' => "29"],
            ['name' => "ORTEGA", 'department_id' => "29"],
            ['name' => "PALOCABILDO", 'department_id' => "29"],
            ['name' => "PIEDRAS PLANADAS", 'department_id' => "29"],
            ['name' => "PRADO", 'department_id' => "29"],
            ['name' => "PURIFICACIÓN", 'department_id' => "29"],
            ['name' => "RIOBLANCO", 'department_id' => "29"],
            ['name' => "RONCESVALLES", 'department_id' => "29"],
            ['name' => "ROVIRA", 'department_id' => "29"],
            ['name' => "SALDAÑA", 'department_id' => "29"],
            ['name' => "SAN ANTONIO", 'department_id' => "29"],
            ['name' => "SAN LUIS", 'department_id' => "29"],
            ['name' => "SANTA ISABEL", 'department_id' => "29"],
            ['name' => "SUÁREZ", 'department_id' => "29"],
            ['name' => "VALLE DE SAN JUAN", 'department_id' => "29"],
            ['name' => "VENADILLO", 'department_id' => "29"],
            ['name' => "VILLAHERMOSA", 'department_id' => "29"],
            ['name' => "VILLARRICA", 'department_id' => "29"],
        ]);
        DB::table('cities')->insert([
            ['name' => "ALCALÁ", 'department_id' => "30"],
            ['name' => "ANDALUCÍA", 'department_id' => "30"],
            ['name' => "ANSERMA NUEVO", 'department_id' => "30"],
            ['name' => "ARGELIA", 'department_id' => "30"],
            ['name' => "BOLÍVAR", 'department_id' => "30"],
            ['name' => "BUENAVENTURA", 'department_id' => "30"],
            ['name' => "BUGA", 'department_id' => "30"],
            ['name' => "BUGALAGRANDE", 'department_id' => "30"],
            ['name' => "CAICEDONIA", 'department_id' => "30"],
            ['name' => "CALI", 'department_id' => "30"],
            ['name' => "CALIMA (DARIEN)", 'department_id' => "30"],
            ['name' => "CANDELARIA", 'department_id' => "30"],
            ['name' => "CARTAGO", 'department_id' => "30"],
            ['name' => "DAGUA", 'department_id' => "30"],
            ['name' => "EL AGUILA", 'department_id' => "30"],
            ['name' => "EL CAIRO", 'department_id' => "30"],
            ['name' => "EL CERRITO", 'department_id' => "30"],
            ['name' => "EL DOVIO", 'department_id' => "30"],
            ['name' => "FLORIDA", 'department_id' => "30"],
            ['name' => "GINEBRA GUACARI", 'department_id' => "30"],
            ['name' => "JAMUNDÍ", 'department_id' => "30"],
            ['name' => "LA CUMBRE", 'department_id' => "30"],
            ['name' => "LA UNIÓN", 'department_id' => "30"],
            ['name' => "LA VICTORIA", 'department_id' => "30"],
            ['name' => "OBANDO", 'department_id' => "30"],
            ['name' => "PALMIRA", 'department_id' => "30"],
            ['name' => "PRADERA", 'department_id' => "30"],
            ['name' => "RESTREPO", 'department_id' => "30"],
            ['name' => "RIO FRÍO", 'department_id' => "30"],
            ['name' => "ROLDANILLO", 'department_id' => "30"],
            ['name' => "SAN PEDRO", 'department_id' => "30"],
            ['name' => "SEVILLA", 'department_id' => "30"],
            ['name' => "TORO", 'department_id' => "30"],
            ['name' => "TRUJILLO", 'department_id' => "30"],
            ['name' => "TULÚA", 'department_id' => "30"],
            ['name' => "ULLOA", 'department_id' => "30"],
            ['name' => "VERSALLES", 'department_id' => "30"],
            ['name' => "VIJES", 'department_id' => "30"],
            ['name' => "YOTOCO", 'department_id' => "30"],
            ['name' => "YUMBO", 'department_id' => "30"],
            ['name' => "ZARZAL", 'department_id' => "30"],
            ['name' => "CARURÚ", 'department_id' => "31"],
            ['name' => "MITÚ", 'department_id' => "31"],
            ['name' => "PACOA", 'department_id' => "31"],
            ['name' => "PAPUNAUA", 'department_id' => "31"],
            ['name' => "TARAIRA", 'department_id' => "31"],
            ['name' => "YAVARATÉ", 'department_id' => "31"],
            ['name' => "CUMARIBO", 'department_id' => "32"],
            ['name' => "LA PRIMAVERA", 'department_id' => "32"],
            ['name' => "PUERTO CARREÑO", 'department_id' => "32"],
            ['name' => "SANTA ROSALIA", 'department_id' => "32"],
        ]);
    }
}
