<?php

namespace Tests;

use App\Models\User;
use Faker\Factory as Faker;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseMigrations;

    protected $faker;

    public function setUp(): void
    {
        parent::setUp();
        $this->faker = Faker::create();
        $this->artisan('passport:install');
        $this->artisan('storage:link');
        $this->seed();
    }

    public function tearDown(): void
    {
        $this->artisan('migrate:reset');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Return request headers needed to interact with the API.
     *
     * @return array of headers.
     */
    public function headers()
    {
        $user = factory(User::class)->create();

        $token = $user->createToken('Token Name')->accessToken;

        return $headers = ['Authorization' => 'Bearer '.$token, 'Accept' => 'application/json'];
    }

    /**
     * @return array
     */
    public function admin()
    {
        $user = factory(User::class)->create();

        //ingresar el role aca

        $token = $user->createToken($user->email)->accessToken;

        return $headers = ['Authorization' => 'Bearer '.$token];
    }
}
